### PR TITLE
new files for generate web service to plugin

### PR DESCRIPTION
**Pull request by juanCarlos123**
code in the plugin for add web_service functions.

blocks_progress_pbinst
 -> Returns Progress Bar instances ids for a given course
Return 
object {
  numevents int   //Number of activities monitored by the Progress Bar
  numattempts int   //Number of activities completed by the user
  progressvalue int   //Percentage of completed activities
} 

blocks_progress_cinfo
-> Returns completion information monitored by a progress bar block
Return
object {
  int   //Progress Bar instance id
}

### CODE REVIEW

**Comment by deraadt** [comment]
Hi, Juan.
Can I ask what you're using these web services for? Is it used for an external intervention tool?

**Comment by juanCarlos123** [comment]
yes , it is used in a connection between Drupal and Moodle, to get the progress

**Comment by juanCarlos123** [comment]
yes , it is used in a connection between Drupal and Moodle, to get the progress

**Comment by juanCarlos123** [comment]
yes , it is used in a connection between Drupal and Moodle, to get the progress

**Comment by juanCarlos123** [comment]
yes , it is used in a connection between Drupal and Moodle, to get the progress

**Pull request closed without merging**
