### PR TITLE
Progress percentage

### PR DESCRIPTION
**Pull request by mikhailjan**
Separate progress percentage from "Mouse over block for info." text and add classes so that it can be styled.

### CODE REVIEW

**Comment by deraadt** [comment]
Hi, Mikhail.

Thanks for sharing your changes.

I can see why you might want to add classes for the percentage and its label. Why do you think this should be above the bar, though?

Michael

**Comment by mikhailjan** [comment]
Hi Michael,

When you hover over the progress bar the progress percentage gets replaced by an icon and name of the activity.

I didn't want it to be hidden (replaced) and I thought having the progress percentage above the bar and the activities below would be a good balance. But that's just how we want to use it.

Of course you can decide, since it's your plugin!

I've attached a screenshot of how I've styled it for my theme.

screen shot 2015-12-09 at 2 15 11 pm

**Comment by deraadt** [comment]
To be honest, I'm not a fan of the percentage. It's a very simple calculation on what could be a variety of different sized tasks. I'd prefer to keep the bar on top.

As a compromise, we could keep the percentage visible when the information about each activity is displayed. That's probably appropriate.

**Comment by mikhailjan** [comment]
Okay lets do that, then I can use CSS to position it. Do you want it below the activity details or between them and the bar?

**Comment by deraadt** [comment]
I've put the progress percentage below the bar and it is shown all the time when it is set in the configuration.

Thanks for your cooperation on this.

**Pull request closed without merging**
