### PR TITLE
Poet 2016030900

### PR DESCRIPTION
**Pull request by mchurchward**
Hi Michael -
I ran this block through the Moodle codechecker, and used phpcbf to automatically fix the violations it could. This pull includes what could be automatically changed. It also has the ".travis.yml" file, which you can ignore if you don't want to use Travis CI integration.
There are still some Moodle code guideline violations that could not be automatically fixed, and some Javascript syntax issues identified.
You can see the pre-auto fix results here - https://travis-ci.org/POETGroup/Moodle-block_progress/builds/114786148
The post auto-fix results are here - https://travis-ci.org/POETGroup/Moodle-block_progress/builds/114788576
If you wish to have these changes, and would like me to fix the other identified coding issues, let me know and I will get someone to do those as well.

### CODE REVIEW

**Comment by deraadt** [comment]
It looks like you're using a different code checker to me, Mike.

**Comment by mchurchward** [comment]
I hope not. The "moodle-plugin-ci" is supposed to be using the same codechecker that Moodle defined for the coding standards. I'll look into that, but do you see some inconsistencies?

**Comment by mchurchward** [comment]
Hi Michael.
I ran the same version of the code through the codechecker provided at the Moodle plugins db (https://moodle.org/plugins/view.php?plugin=local_codechecker) and got the same results (see attached text file), with the exception that the plugin didn't flag problems with the unary "?" syntax. I'll have to check to see which of the two checkers is accurate there. But the spacing issues around the operators that were fixed by that script does fix the issues from both codecheckers.

[block_progress.txt](https://github.com/deraadt/Moodle-block_progress/files/169160/block_progress.txt)

**Comment by mchurchward** [comment]
Hi Michael...
More up to date information...
I loaded the local codechecker I used with the one from moodlehq's github (moodlehq/moodle-local_codechecker.git) and reran against the progress block. That gave me identical results to the one I sent from Travis CI.
Here's the most recent version check in Travis CI.
I have attached the text from the Moodle plugin:
[block_progress.txt](https://github.com/deraadt/Moodle-block_progress/files/169362/block_progress.txt)
The most recent update to HQ's codechecker was on Feb, 25, so I presume its current.

**Pull request closed without merging**
