### PR TITLE
Adds support for H5P plugin

### PR DESCRIPTION
**Pull request by juho-jaakkola**
Information about the plugin:
- https://h5p.org/
- https://moodle.org/plugins/mod_hvp

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Is Github the correct way of adding the features to the plugin?

**Comment by juho-jaakkola** [comment]
I someone reading the pull requests and comments here at Github?

**Comment by juho-jaakkola** [comment]
Ok, I now found out that this block has been replaced with: https://github.com/deraadt/moodle-block_completion_progress

**Comment by deraadt** [comment]
Thanks for working on this. Sorry, I'm not working on the Progress Bar block any more. The Completion Progress block should support your activities without customisation, if they support completion.

**Pull request closed without merging**
